name: pytest

on:
  pull_request:
    branches: [main]
    paths:
      - "**.py"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/pytest.yml"
  push:
    branches: [main]
    paths:
      - "**.py"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/pytest.yml"
jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      UV_FROZEN: "1"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv.
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: PyTest
        run: uv run pytest --cov=src --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jbcoe/human.resource.machine
